Scala steward configuration
finagle/finch pull request #1457
Opened 2022-04-05 16:50 UTC by tpetillot

chore: use circe version for circe-fs2
---

**Motivation:**
Must be aligned

chore: add scala steward configuration

---

**Modification:**
* freeze `cats-effect` to major version 2
* freeze `fs2-core` to major version (next use CE3)
* freeze `circe-fs2` to minor version (next use fs2 > v3)

2022-04-05 20:20 UTC, joroKr21 requested changes
Another thing I wonder about is if we should support both Cats Effect 2.x and 3.x on separate branches or just aim to move to 3.x soonish.

2022-04-05 20:20 UTC, joroKr21 commented on .scala-steward.conf
> +  { groupId = "org.typelevel", artifactId="cats-effect", version="x." },
```suggestion
  { groupId = "co.fs2", artifactId="fs2-core", version="2." },
  { groupId = "io.circe", version="0.13." },
  { groupId = "org.typelevel", artifactId="cats-effect", version="2." },
```

2022-04-06 09:14 UTC, tpetillot commented
3.x soonish sound good to me (it'll motivate us to do the upgrade, and quit quill)

2022-04-06 09:21 UTC, tpetillot commented
I think we're good for a release after this one? (which is not required into the release at all)

2022-04-06 10:33 UTC, joroKr21 commented on .scala-steward.conf
> +  { groupId = "io.circe", artifactId="circe-fs2", version="0.13." },
I think we need to pin all of Circe
```suggestion
  { groupId = "io.circe", version="0.13." },
```

2022-04-06 10:34 UTC, joroKr21 commented
> I think we're good for a release after this one? (which is not required into the release at all)

Yeah, feel free to cut a release 👍 

> Then, I may check what's needed to upgrade to CE3

Awesome!

2022-04-06 10:34 UTC, joroKr21 approved these changes

2022-04-06 11:26 UTC, merged

2022-04-06 12:44 UTC, tpetillot commented
756cea1a61ae82418ba7c3413f05448d71dde402 release doesn't seems to be triggered...